### ISSUE TITLE
CentOS 6.6 64bit make errors

### ISSUE THREAD

**Issue by centminmod** [MediaFire/mediafire-fuse#16] opened 2015-01-28 15:18 UTC
Seems to be getting make errors on CentOS 6.6

cmake

    build]# cmake ..
    -- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
    -- Found CURL: /usr/lib64/libcurl.so (found version "7.19.7") 
    -- Found FUSE: /lib64/libfuse.so (Required is at least version "2.9") 
    -- Found Jansson: /usr/lib64/libjansson.so (found suitable version "2.6", minimum required is "2.5") 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /svr-setup/mediafire-fuse/build
    
make    
    
    
    build]# make
    Scanning dependencies of target mfapi
    [ 44%] Built target mfapi
    Scanning dependencies of target mfutils
    [ 52%] Built target mfutils
    Scanning dependencies of target mediafire-fuse
    [ 54%] Building C object CMakeFiles/mediafire-fuse.dir/fuse/hashtbl.c.o
    cc1: warnings being treated as errors
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:85: error: declaration does not declare anything
    /svr-setup/mediafire-fuse/fuse/hashtbl.c: In function ‘folder_tree_store’:
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:256: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:258: error: ‘struct h_entry’ has no member named ‘parent_offs’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:273: error: ‘struct h_entry’ has no member named ‘parent_offs’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:286: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c: In function ‘folder_tree_load’:
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:383: error: ‘struct h_entry’ has no member named ‘parent_offs’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:384: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c: In function ‘folder_tree_allocate_entry’:
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:885: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c: In function ‘folder_tree_add_file’:
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:994: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c: In function ‘folder_tree_add_folder’:
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:1068: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c: In function ‘folder_tree_remove’:
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:1225: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:1232: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:1234: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c: In function ‘folder_tree_housekeep’:
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:1634: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:1661: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:1700: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:1704: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c: In function ‘folder_tree_debug_helper’:
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:1736: error: ‘struct h_entry’ has no member named ‘parent’
    /svr-setup/mediafire-fuse/fuse/hashtbl.c:1742: error: ‘struct h_entry’ has no member named ‘parent’
    make[2]: *** [CMakeFiles/mediafire-fuse.dir/fuse/hashtbl.c.o] Error 1
    make[1]: *** [CMakeFiles/mediafire-fuse.dir/all] Error 2
    make: *** [all] Error 2

**Comment by TragicWarrior** [comment] 2015-01-28 15:31
@centminmod , what version of GCC are you using?

**Comment by centminmod** [comment] 2015-01-28 16:29
@TragicWarrior gcc = 4.4.7 

    gcc -v
    Using built-in specs.
    Target: x86_64-redhat-linux
    Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib -    -with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
    Thread model: posix
    gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

**Comment by TragicWarrior** [comment] 2015-01-28 16:46
@centminmod , i pushed a small fix to the branch "fmsfix".  please try that.  it's not an elegant solution, i just want to see if it fixes your issue.  i saw a similar issue on slackware 10.

when you build, you'll need to:

make clean
remove the CMakeCache.txt
run cmake -G "Unix Makefiles" to recreate your Makefile

please let me know if this fixes your issue or not.

**Comment by centminmod** [comment] 2015-01-28 17:00
@TragicWarrior perfect fixed and seems to have installed fine now :)

    build]# make
    -- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
    -- Found CURL: /usr/lib64/libcurl.so (found version "7.19.7") 
    -- Found FUSE: /lib64/libfuse.so (Required is at least version "2.9") 
    -- Found Jansson: /usr/lib64/libjansson.so (found suitable version "2.6", minimum required is "2.5") 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /svr-setup/mediafire-fuse/build
    Scanning dependencies of target mfutils
    [  1%] Building C object CMakeFiles/mfutils.dir/utils/http.c.o
    [  3%] Building C object CMakeFiles/mfutils.dir/utils/strings.c.o
    [  4%] Building C object CMakeFiles/mfutils.dir/utils/stringv.c.o
    [  6%] Building C object CMakeFiles/mfutils.dir/utils/xdelta3.c.o
    [  8%] Building C object CMakeFiles/mfutils.dir/utils/hash.c.o
    [  8%] Built target mfutils
    Scanning dependencies of target mfapi
    [  9%] Building C object CMakeFiles/mfapi.dir/mfapi/mfconn.c.o
    [ 11%] Building C object CMakeFiles/mfapi.dir/mfapi/file.c.o
    [ 13%] Building C object CMakeFiles/mfapi.dir/mfapi/folder.c.o
    [ 14%] Building C object CMakeFiles/mfapi.dir/mfapi/patch.c.o
    [ 16%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls.c.o
    [ 18%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_get_info.c.o
    [ 19%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_move.c.o
    [ 21%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_update.c.o
    [ 22%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/user_get_info.c.o
    [ 24%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_get_links.c.o
    [ 26%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/file_delete.c.o
    [ 27%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/user_get_session_token.c.o
    [ 29%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_get_info.c.o
    [ 31%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_create.c.o
    [ 32%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_get_content.c.o
    [ 34%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_delete.c.o
    [ 36%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_move.c.o
    [ 37%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/folder_update.c.o
    [ 39%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/device_get_status.c.o
    [ 40%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/device_get_changes.c.o
    [ 42%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/device_get_patch.c.o
    [ 44%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/device_get_updates.c.o
    [ 45%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/upload_check.c.o
    [ 47%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/upload_instant.c.o
    [ 49%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/upload_simple.c.o
    [ 50%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/upload_patch.c.o
    [ 52%] Building C object CMakeFiles/mfapi.dir/mfapi/apicalls/upload_poll_upload.c.o
    [ 52%] Built target mfapi
    Scanning dependencies of target mediafire-fuse
    [ 54%] Building C object CMakeFiles/mediafire-fuse.dir/fuse/main.c.o
    [ 55%] Building C object CMakeFiles/mediafire-fuse.dir/fuse/hashtbl.c.o
    [ 57%] Building C object CMakeFiles/mediafire-fuse.dir/fuse/filecache.c.o
    [ 59%] Building C object CMakeFiles/mediafire-fuse.dir/fuse/operations.c.o
    Linking C executable mediafire-fuse
    [ 59%] Built target mediafire-fuse
    Scanning dependencies of target mediafire-shell
    [ 60%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/main.c.o
    [ 62%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/mfshell.c.o
    [ 63%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/folder.c.o
    [ 65%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/auth.c.o
    [ 67%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/chdir.c.o
    [ 68%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/debug.c.o
    [ 70%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/file.c.o
    [ 72%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/get.c.o
    [ 73%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/put.c.o
    [ 75%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/help.c.o
    [ 77%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/host.c.o
    [ 78%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/lcd.c.o
    [ 80%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/links.c.o
    [ 81%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/list.c.o
    [ 83%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/lpwd.c.o
    [ 85%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/mkdir.c.o
    [ 86%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/pwd.c.o
    [ 88%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/whoami.c.o
    [ 90%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/rmdir.c.o
    [ 91%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/rm.c.o
    [ 93%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/status.c.o
    [ 95%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/changes.c.o
    [ 96%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/config.c.o
    [ 98%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/options.c.o
    [100%] Building C object CMakeFiles/mediafire-shell.dir/mfshell/commands/updates.c.o
    Linking C executable mediafire-shell
    [100%] Built target mediafire-shell

make install

    build]# make install
    [  8%] Built target mfutils
    [ 52%] Built target mfapi
    [ 59%] Built target mediafire-fuse
    [100%] Built target mediafire-shell
    Linking C executable CMakeFiles/CMakeRelink.dir/mediafire-fuse
    Linking C executable CMakeFiles/CMakeRelink.dir/mediafire-shell
    Install the project...
    -- Install configuration: ""
    -- Installing: /usr/local/bin/mediafire-fuse
    -- Installing: /usr/local/bin/mediafire-shell

**Comment by TragicWarrior** [comment] 2015-01-28 17:05
@centminmod , thanks for testing.  i created a merge request for @josch .  he might know of a more elegant way of handling this.  either way, some fix will be merged into master soon.

**Comment by josch** [comment] 2015-01-28 17:35
The problem is, that I was born too late and got used to using anonymous unions. But with older gcc they are only available either with `-fms-extensions` or with `-std=c1x` since gcc-4.6 or with `-std=c11` since gcc-4.7 since anonymous unions are a C11 feature: http://en.wikipedia.org/wiki/C11_(C_standard_revision).

So to fix this problem, I converted the anonymous union in fuse/hashtbl.c into a named one and also removed the current use of `-fms-extensions` from the CMakeLists.txt because it should not be needed anymore.

Please check whether this works on CentOS and then the pull request can be closed too.

**Comment by centminmod** [comment] 2015-01-28 17:41
@josch did fresh install on CentOS 6.6 64bit and works fine with master branch :)

Been waiting for a official fuse/mount supported cloud storage offering for ages so thanks

cheers !

George

**Comment by TragicWarrior** [comment] 2015-01-28 18:13
@centminmod , marking this closed.  thanks for reporting the issue.

**Closed by TragicWarrior** 2015-01-28 18:13 UTC
